name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: make collect-dependencies
      shell: bash
    - name: Run Benchmarks
      run: make test
      shell: bash
    - name: Generate Reports
      run: make gen-report
      shell: bash
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Benchmark result
        path: scripts/output.md
