name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - uses: actions/setup-node@v1
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: make collect-dependencies
    - name: Run Benchmarks
      run: make test
    - name: Generate Reports
      run: make gen-report
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Benchmark result
        path: scripts/output.md
